{% set version = "0.14.0" %}
{% set hash = "1caeaadd0dd4b6b4504bd7961d1851c9397b009e2cc1a79aa7be487278207e84" %}
{% set name = "thrift" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/apache/thrift/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install lib/py --no-deps -vv

requirements:
  build:
    - python
    - cross-python
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
  host:
    - pip
    - python
    - six >=1.7.2
  run:
    - python
    - six >=1.7.2

test:
  imports:
    - thrift
    - thrift.protocol
    - thrift.server
    - thrift.transport

about:
  home: http://thrift.apache.org
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Python bindings for the Apache Thrift RPC system'

extra:
  recipe-maintainers:
    - mariusvniekerk
    - marshall245
