{% set version = "0.17.0" %}
{% set hash_type = "sha256" %}
{% set hash = "f5888bcd3b8de40c2c2ab86896867ad9b18510deb412cba3e5da76fb4c604c29" %}
{% set name = "thrift" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/apache/thrift/archive/refs/tags/v{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 2
  script: {{ PYTHON }} -m pip install ./lib/py -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - setuptools
    - six >=1.7.2
    - wheel
  run:
    - python
    - six >=1.7.2

test:
  imports:
    - thrift
    - thrift.protocol
    - thrift.server
    - thrift.transport
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://thrift.apache.org
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  license_url: https://github.com/apache/thrift/blob/master/LICENSE
  description: |
    Thrift is a lightweight, language-independent software stack for point-to-point RPC implementation.
    Thrift provides clean abstractions and implementations for data transport, data serialization, and application level processing.
  summary: Python bindings for the Apache Thrift RPC system
  dev_url: https://github.com/apache/thrift
  doc_url: https://thrift.apache.org/docs/
  doc_source_url: https://github.com/apache/thrift/tree/v{{ version }}/doc

extra:
  recipe-maintainers:
    - mariusvniekerk
    - ericdill
    - marshall245
