{% set version = "0.13.0" %}
{% set hash_type = "sha256" %}
{% set hash = "9af1c86bf73433afc6010ed376a6c6aca2b54099cc0d61895f640870a9ae7d89" %}
{% set name = "thrift" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
 
requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"    
  host:
    - pip
    - python
    - six >=1.7.2
  run: 
    - python
    - six >=1.7.2

test:
  imports:
    - thrift
    - thrift.protocol
    - thrift.server
    - thrift.transport

about:
  home: http://thrift.apache.org
  license: Apache 2.0
  summary: 'Python bindings for the Apache Thrift RPC system'

extra:
  recipe-maintainers:
    - mariusvniekerk
    - ericdill
    - marshall245
