{% set version = "0.19.0" %}
{% set hash = "6428911db505702c51f7d993155a4a4c8afee83fdd021b52f2eccd8d34780629" %}
{% set name = "thrift" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/apache/thrift/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install lib/py --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - six >=1.7.2
  run:
    - python
    - six >=1.7.2

test:
  imports:
    - thrift
    - thrift.protocol
    - thrift.server
    - thrift.transport

about:
  home: http://thrift.apache.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Python bindings for the Apache Thrift RPC system

extra:
  recipe-maintainers:
    - mariusvniekerk
    - marshall245
